language: node_js
node_js:
  - '6'
  - '7'
  - '8'

before_install:
  - node -v
  - npm -v

install:
  - npm install -g npm@latest
  - npm install -g gulp-cli@latest

before_script:
  - npm install

script:
  - npm run build
